server:
  port: 8088
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Phronima6/bank-app-config
          refreshRate: 10