spring:
  application:
    name: exchange
  config:
    import: optional:configserver:http://localhost:8088
  profiles:
    active: default
  cloud:
    config:
      label: main

exchange:
  rate-ranges:
    USD:
      min: 7500
      max: 8500
    CNY:
      min: 1000
      max: 1100